"prefix": "portal-js",
        "body": [
            "function addRow() {",
            "    const serialNumber = document.getElementById('serialNumber').value;",
            "    const clientTd = document.getElementById('clientTd').value;",
            "    const hostRebootDetails = document.getElementById('hostRebootDetails').value;",
            "    const rcaDetails = document.getElementById('rcaDetails').value;",
            "",
            "    const table = document.getElementById('data-table').getElementsByTagName('tbody')[0];",
            "    const newRow = table.insertRow();",
            "",
            "    newRow.insertCell(0).innerText = serialNumber;",
            "    newRow.insertCell(1).innerText = clientTd;",
            "    newRow.insertCell(2).innerText = hostRebootDetails;",
            "    newRow.insertCell(3).innerText = rcaDetails;",
            "",
            "    document.getElementById('data-form').reset();",
            "}",
            "",
            "function pasteExcelData() {",
            "    const excelData = document.getElementById('excelData').value;",
            "    const rows = excelData.split('\\n');",
            "    const table = document.getElementById('data-table').getElementsByTagName('tbody')[0];",
            "",
            "    rows.forEach(row => {",
            "        const columns = row.split('\\t');",
            "        if (columns.length === 4) {",
            "            const newRow = table.insertRow();",
            "            columns.forEach(column => {",
            "                const newCell = newRow.insertCell();",
            "                newCell.innerText = column;",
            "            });",
            "        }",
            "    });",
            "}"
        ],
        "description": "JavaScript functions for the basic portal"
    }
}
